/**
 * Templates garantizados por tipo de artefacto.
 * Se usan como último fallback cuando la IA no puede generar el contenido.
 * Proporcionan una base profesional que el consultor puede completar.
 */
import type { TipoArtefacto } from '@/types/database'

export const TEMPLATES_GARANTIZADOS: Record<TipoArtefacto, Record<string, unknown>> = {
  sipoc: {
    proveedores: ['Proveedor principal', 'Proveedor secundario'],
    entradas: ['Solicitud formal', 'Información de respaldo', 'Documentación requerida'],
    proceso: 'Proceso de gestión que incluye recepción, validación, procesamiento y entrega del resultado al cliente interno.',
    salidas: ['Resultado procesado', 'Confirmación de entrega', 'Registro actualizado'],
    clientes: ['Área solicitante', 'Cliente interno principal'],
    notas: 'Completar con información específica del proceso',
    limite_entrada: 'Recepción de solicitud formal',
    limite_salida: 'Entrega y confirmación al solicitante',
  },
  as_is: {
    descripcion_estado_actual: 'El proceso opera de manera predominantemente manual con coordinación por correo electrónico y planillas. Los tiempos de ciclo son variables y existen puntos de mejora en trazabilidad y control.',
    actores: ['Jefe de Área', 'Analista', 'Operador', 'Supervisor'],
    sistemas_involucrados: ['Correo electrónico', 'Planillas Excel', 'ERP corporativo'],
    pasos: [
      { orden: 1, descripcion: 'Recepción de solicitud', responsable: 'Analista', duracion_estimada: '30 min', sistema: 'Correo' },
      { orden: 2, descripcion: 'Validación de información', responsable: 'Analista', duracion_estimada: '1 hora', sistema: 'Planilla' },
      { orden: 3, descripcion: 'Procesamiento principal', responsable: 'Operador', duracion_estimada: '3 horas', sistema: 'ERP' },
      { orden: 4, descripcion: 'Revisión y aprobación', responsable: 'Supervisor', duracion_estimada: '1 hora', sistema: 'Correo' },
      { orden: 5, descripcion: 'Cierre y notificación', responsable: 'Analista', duracion_estimada: '30 min', sistema: 'Correo' },
    ],
    puntos_dolor: ['Procesos manuales propensos a error', 'Falta de trazabilidad en tiempo real', 'Coordinación ineficiente entre áreas', 'Tiempo de ciclo variable e impredecible'],
    tiempo_ciclo_actual: '6-8 horas',
    volumen_transacciones: 'Variable — completar con dato real',
  },
  bpmn: {
    titulo: 'Proceso Principal',
    nodes: [
      { id: '1', type: 'start', position: { x: 400, y: 50 }, data: { label: 'Inicio del Proceso' } },
      { id: '2', type: 'task', position: { x: 400, y: 200 }, data: { label: 'Recepción de solicitud', actor: 'Analista' } },
      { id: '3', type: 'task', position: { x: 400, y: 350 }, data: { label: 'Validación de información', actor: 'Analista' } },
      { id: '4', type: 'decision', position: { x: 400, y: 500 }, data: { label: '¿Información completa?' } },
      { id: '5', type: 'task', position: { x: 700, y: 650 }, data: { label: 'Solicitar datos faltantes', actor: 'Analista' } },
      { id: '6', type: 'task', position: { x: 400, y: 650 }, data: { label: 'Procesamiento del caso', actor: 'Operador' } },
      { id: '7', type: 'task', position: { x: 400, y: 800 }, data: { label: 'Control de calidad', actor: 'Supervisor' } },
      { id: '8', type: 'decision', position: { x: 400, y: 950 }, data: { label: '¿Aprobado?' } },
      { id: '9', type: 'task', position: { x: 700, y: 1100 }, data: { label: 'Devolver con observaciones', actor: 'Operador' } },
      { id: '10', type: 'task', position: { x: 400, y: 1100 }, data: { label: 'Aprobación y firma', actor: 'Jefe de Área' } },
      { id: '11', type: 'task', position: { x: 400, y: 1250 }, data: { label: 'Notificación y cierre', actor: 'Analista' } },
      { id: '12', type: 'end', position: { x: 400, y: 1400 }, data: { label: 'Fin del Proceso' } },
    ],
    edges: [
      { id: 'e1-2', source: '1', target: '2', animated: true },
      { id: 'e2-3', source: '2', target: '3' },
      { id: 'e3-4', source: '3', target: '4' },
      { id: 'e4-5', source: '4', target: '5', label: 'No' },
      { id: 'e4-6', source: '4', target: '6', label: 'Sí' },
      { id: 'e5-3', source: '5', target: '3' },
      { id: 'e6-7', source: '6', target: '7' },
      { id: 'e7-8', source: '7', target: '8' },
      { id: 'e8-9', source: '8', target: '9', label: 'No' },
      { id: 'e8-10', source: '8', target: '10', label: 'Sí' },
      { id: 'e9-6', source: '9', target: '6' },
      { id: 'e10-11', source: '10', target: '11' },
      { id: 'e11-12', source: '11', target: '12' },
    ],
  },
  flujograma: {
    titulo: 'Flujograma Operacional',
    nodes: [
      { id: '1', type: 'start', position: { x: 400, y: 50 }, data: { label: 'Inicio' } },
      { id: '2', type: 'task', position: { x: 400, y: 200 }, data: { label: 'Recibir y registrar solicitud' } },
      { id: '3', type: 'task', position: { x: 400, y: 350 }, data: { label: 'Verificar requisitos' } },
      { id: '4', type: 'decision', position: { x: 400, y: 500 }, data: { label: '¿Cumple requisitos?' } },
      { id: '5', type: 'task', position: { x: 700, y: 650 }, data: { label: 'Devolver para corrección' } },
      { id: '6', type: 'task', position: { x: 400, y: 650 }, data: { label: 'Procesar solicitud' } },
      { id: '7', type: 'task', position: { x: 400, y: 800 }, data: { label: 'Revisar y aprobar' } },
      { id: '8', type: 'end', position: { x: 400, y: 950 }, data: { label: 'Fin' } },
    ],
    edges: [
      { id: 'e1-2', source: '1', target: '2', animated: true },
      { id: 'e2-3', source: '2', target: '3' },
      { id: 'e3-4', source: '3', target: '4' },
      { id: 'e4-5', source: '4', target: '5', label: 'No' },
      { id: 'e4-6', source: '4', target: '6', label: 'Sí' },
      { id: 'e5-3', source: '5', target: '3' },
      { id: 'e6-7', source: '6', target: '7' },
      { id: 'e7-8', source: '7', target: '8' },
    ],
  },
  historias_usuario: {
    historias: [
      { id: 'HU-01', rol: 'Analista de proceso', necesidad: 'registrar solicitudes de forma digital y trazable', beneficio: 'reducir errores y tiempo de procesamiento', prioridad: 'alta', criterios_aceptacion: ['Formulario digital disponible', 'Validación automática de campos', 'Número correlativo asignado automáticamente'], puntos_historia: 5, estado: 'pendiente' },
      { id: 'HU-02', rol: 'Jefe de Área', necesidad: 'visualizar el estado de las solicitudes en tiempo real', beneficio: 'tomar decisiones oportunas y gestionar la carga de trabajo', prioridad: 'alta', criterios_aceptacion: ['Dashboard con estado actualizado', 'Alertas de vencimiento de SLA', 'Reporte exportable'], puntos_historia: 8, estado: 'pendiente' },
      { id: 'HU-03', rol: 'Operador', necesidad: 'recibir instrucciones claras para cada tarea', beneficio: 'ejecutar el proceso correctamente y sin reprocesos', prioridad: 'media', criterios_aceptacion: ['Checklist digital por operación', 'Guía de pasos en pantalla', 'Alerta si se omite un paso crítico'], puntos_historia: 3, estado: 'pendiente' },
      { id: 'HU-04', rol: 'Supervisor', necesidad: 'aprobar solicitudes desde cualquier dispositivo', beneficio: 'reducir tiempos de espera en el proceso de aprobación', prioridad: 'alta', criterios_aceptacion: ['Aprobación móvil disponible', 'Información completa del caso al aprobar', 'Registro de la aprobación con fecha y hora'], puntos_historia: 5, estado: 'pendiente' },
    ],
  },
  raci: {
    actividades: ['Recepción y registro de solicitud', 'Validación de información', 'Procesamiento operacional', 'Control de calidad', 'Aprobación ejecutiva', 'Cierre y notificación'],
    roles: ['Analista', 'Operador', 'Supervisor', 'Jefe de Área'],
    matriz: {
      'Recepción y registro de solicitud': { Analista: 'R', Operador: 'I', Supervisor: 'I', 'Jefe de Área': 'A' },
      'Validación de información': { Analista: 'R', Operador: 'C', Supervisor: 'I', 'Jefe de Área': 'A' },
      'Procesamiento operacional': { Analista: 'I', Operador: 'R', Supervisor: 'C', 'Jefe de Área': 'A' },
      'Control de calidad': { Analista: 'I', Operador: 'C', Supervisor: 'R', 'Jefe de Área': 'A' },
      'Aprobación ejecutiva': { Analista: 'I', Operador: 'I', Supervisor: 'C', 'Jefe de Área': 'R' },
      'Cierre y notificación': { Analista: 'R', Operador: 'I', Supervisor: 'I', 'Jefe de Área': 'A' },
    },
    leyenda: { R: 'Responsable de ejecutar', A: 'Aprobador/Accountable', C: 'Consultado', I: 'Informado' },
  },
  riesgo_control: {
    riesgos: [
      { id: 'R-01', descripcion: 'Errores en el ingreso de información', categoria: 'operacional', probabilidad: 'media', impacto: 'alto', nivel_riesgo: 'alto', control: 'Validación automática de campos y revisión por segundo par de ojos', tipo_control: 'preventivo', responsable: 'Supervisor', estado: 'activo' },
      { id: 'R-02', descripcion: 'Incumplimiento de plazos (SLA)', categoria: 'operacional', probabilidad: 'alta', impacto: 'medio', nivel_riesgo: 'medio', control: 'Alertas automáticas de vencimiento y seguimiento diario', tipo_control: 'detectivo', responsable: 'Jefe de Área', estado: 'activo' },
      { id: 'R-03', descripcion: 'Pérdida de información o documentos', categoria: 'tecnológico', probabilidad: 'baja', impacto: 'alto', nivel_riesgo: 'medio', control: 'Respaldo digital obligatorio y política de retención documental', tipo_control: 'preventivo', responsable: 'TI', estado: 'activo' },
      { id: 'R-04', descripcion: 'Incumplimiento normativo o regulatorio', categoria: 'regulatorio', probabilidad: 'baja', impacto: 'alto', nivel_riesgo: 'medio', control: 'Checklist de cumplimiento regulatorio en cada transacción', tipo_control: 'preventivo', responsable: 'Jefe de Área', estado: 'activo' },
    ],
  },
  kpi_sla: {
    indicadores: [
      { nombre: 'Tiempo de ciclo promedio', descripcion: 'Tiempo total desde recepción hasta cierre', formula: 'Fecha/hora cierre - Fecha/hora apertura', unidad: 'horas', linea_base: 'Por medir', meta: '4 horas', frecuencia: 'mensual', dueno: 'Jefe de Área', fuente_dato: 'Sistema de gestión', sla: 'Máximo 8 horas hábiles', tipo: 'tiempo' },
      { nombre: 'Tasa de reprocesos', descripcion: 'Porcentaje de casos que requieren corrección', formula: '(Casos con reproceso / Total casos) × 100', unidad: '%', linea_base: 'Por medir', meta: '< 5%', frecuencia: 'mensual', dueno: 'Supervisor', fuente_dato: 'Registro de operaciones', sla: 'Máximo 10%', tipo: 'calidad' },
      { nombre: 'Cumplimiento de SLA', descripcion: 'Porcentaje de casos resueltos en el plazo acordado', formula: '(Casos en plazo / Total casos) × 100', unidad: '%', linea_base: 'Por medir', meta: '95%', frecuencia: 'mensual', dueno: 'Jefe de Área', fuente_dato: 'Sistema de gestión', sla: 'Mínimo 90%', tipo: 'eficiencia' },
      { nombre: 'Satisfacción del cliente interno', descripcion: 'NPS del área solicitante', formula: 'Promedio encuesta post-servicio', unidad: 'puntos', linea_base: 'Por medir', meta: '85', frecuencia: 'trimestral', dueno: 'Jefe de Área', fuente_dato: 'Encuesta digital', sla: 'Mínimo 75 puntos', tipo: 'calidad' },
    ],
    financiero: { ahorro_estimado: 'A cuantificar tras implementación', roi_estimado: 'A proyectar' },
  },
  diagnostico: {
    nivel_madurez: 2,
    nivel_madurez_descripcion: 'Proceso definido pero con ejecución inconsistente y limitada automatización',
    fortalezas: ['Personal con experiencia en el proceso', 'Infraestructura tecnológica disponible', 'Voluntad de mejora del equipo', 'Soporte de la dirección'],
    debilidades: ['Procesos predominantemente manuales', 'Falta de estandarización formal', 'Documentación desactualizada', 'Métricas de desempeño no implementadas'],
    oportunidades: ['Digitalización y automatización del proceso', 'Integración con sistemas corporativos', 'Mejora de la experiencia del cliente interno', 'Reducción de costos operacionales'],
    amenazas: ['Resistencia al cambio del equipo', 'Presupuesto limitado para tecnología', 'Cambios regulatorios frecuentes', 'Dependencia de personas clave'],
    brechas_criticas: ['Brecha entre proceso documentado y proceso ejecutado', 'Ausencia de trazabilidad y control en tiempo real', 'Falta de indicadores de desempeño operacionales'],
    recomendaciones_prioritarias: ['Digitalizar el proceso con herramienta de workflow', 'Implementar indicadores de desempeño (KPIs)', 'Estandarizar mediante procedimientos documentados'],
    conclusion: 'El proceso tiene potencial significativo de mejora. La prioridad es la digitalización para ganar trazabilidad y consistencia en la ejecución.',
  },
  to_be: {
    descripcion_estado_futuro: 'Proceso completamente digitalizado con flujo automatizado, trazabilidad total y métricas en tiempo real, reduciendo el tiempo de ciclo en un 70% y eliminando reprocesos.',
    actores: ['Analista Digital', 'Operador', 'Supervisor', 'Jefe de Área', 'Sistema BPM'],
    sistemas_requeridos: ['Plataforma BPM o workflow digital', 'ERP corporativo integrado', 'Portal de autoservicio para solicitantes', 'Dashboard de analytics'],
    pasos: [
      { orden: 1, descripcion: 'Ingreso digital de solicitud por portal de autoservicio', responsable: 'Solicitante', automatizado: true, herramienta: 'Portal web', mejora_vs_asis: 'Elimina correos y formularios físicos' },
      { orden: 2, descripcion: 'Validación automática de requisitos por motor de reglas', responsable: 'Sistema BPM', automatizado: true, herramienta: 'Motor de reglas', mejora_vs_asis: 'De 1 hora a 2 minutos' },
      { orden: 3, descripcion: 'Asignación automática al operador disponible', responsable: 'Sistema BPM', automatizado: true, herramienta: 'BPM', mejora_vs_asis: 'Elimina asignación manual' },
      { orden: 4, descripcion: 'Procesamiento con guía digital paso a paso', responsable: 'Operador', automatizado: false, herramienta: 'BPM + ERP', mejora_vs_asis: 'Guía contextual reduce errores' },
      { orden: 5, descripcion: 'Aprobación digital con firma electrónica', responsable: 'Jefe de Área', automatizado: false, herramienta: 'BPM móvil', mejora_vs_asis: 'Aprobación en minutos desde cualquier lugar' },
      { orden: 6, descripcion: 'Notificación automática y cierre en sistema', responsable: 'Sistema BPM', automatizado: true, herramienta: 'BPM + Email', mejora_vs_asis: 'Cierre inmediato sin intervención manual' },
    ],
    metricas_objetivo: [
      { nombre: 'Tiempo de ciclo', valor_actual: '8 horas', valor_objetivo: '2 horas', plazo: '6 meses' },
      { nombre: 'Tasa de reprocesos', valor_actual: 'Por medir', valor_objetivo: '< 3%', plazo: '6 meses' },
    ],
    mejoras_respecto_asis: ['75% reducción en tiempo de ciclo', 'Eliminación de errores por digitación manual', 'Trazabilidad completa de todas las transacciones', 'Reportería automática para la dirección'],
    tiempo_ciclo_objetivo: '2 horas',
    reduccion_estimada: '75%',
  },
  dashboard_brechas: {
    resumen_ejecutivo: 'El proceso muestra brechas relevantes en automatización y control que representan una oportunidad de mejora del 60-70% en eficiencia operacional.',
    comparativo: [
      { dimension: 'Nivel de automatización', valor_asis: '10-20% automatizado', valor_tobe: '80% automatizado', brecha: '60+ puntos porcentuales', impacto: 'alto', iniciativa: 'Implementar plataforma BPM', esfuerzo: 'alto' },
      { dimension: 'Tiempo de ciclo', valor_asis: '6-8 horas', valor_tobe: '1-2 horas', brecha: '75% de reducción', impacto: 'alto', iniciativa: 'Digitalización y automatización de flujo', esfuerzo: 'medio' },
      { dimension: 'Trazabilidad', valor_asis: 'Parcial (correos y planillas)', valor_tobe: 'Total en tiempo real', brecha: 'Sin trazabilidad confiable', impacto: 'alto', iniciativa: 'Sistema de gestión digital', esfuerzo: 'medio' },
      { dimension: 'Satisfacción cliente interno', valor_asis: 'No medido', valor_tobe: '> 85 puntos NPS', brecha: 'Sin métricas establecidas', impacto: 'medio', iniciativa: 'Implementar encuesta post-servicio', esfuerzo: 'bajo' },
    ],
    quick_wins: ['Digitalizar formularios de solicitud', 'Implementar notificaciones automáticas por correo', 'Crear tabla de seguimiento compartida en tiempo real'],
    indice_brecha_global: 68,
    conclusion: 'Priorizar la digitalización del flujo principal para obtener el mayor impacto. Los quick wins permiten demostrar valor en las primeras 4 semanas.',
  },
  cierre_ejecutivo: {
    titulo_proyecto: 'Transformación del Proceso — Entregable de Consultoría',
    resumen_proyecto: 'AICOUNTS Consultores completó el análisis y modelamiento del proceso, identificando oportunidades de mejora que permitirán reducir el tiempo de ciclo en un 70% y los costos operacionales en un 25% mediante digitalización y automatización.',
    procesos_transformados: 1,
    reduccion_tiempo_ciclo_estimada: '70%',
    ahorro_estimado: '25% en costos operacionales',
    roi_estimado: '> 150% en 18 meses',
    logros_principales: ['Diagnóstico completo del estado actual (AS-IS)', 'Identificación de brechas críticas y oportunidades', 'Diseño del estado futuro optimizado (TO-BE)', 'Roadmap de implementación en 3 fases', '8 artefactos metodológicos generados'],
    proximos_pasos: ['Presentar hallazgos a la dirección', 'Aprobar el plan de implementación', 'Iniciar Fase 1: Quick Wins (primeras 4 semanas)'],
    recomendacion_ceo: 'Aprobar el plan de transformación e iniciar inmediatamente con los quick wins para capturar valor temprano y demostrar el ROI de la iniciativa.',
    fecha_cierre: '',
    clasificacion_exito: 'exitoso',
  },
  checklist: {
    frecuencia_uso: 'por_transaccion',
    checklists: [
      {
        rol: 'Analista',
        descripcion_rol: 'Responsable de recepción, registro y coordinación de solicitudes',
        items: [
          { descripcion: 'Verificar que la solicitud esté completa con todos los campos requeridos', fase: 'preparacion', critico: true, nota: 'No procesar si hay campos vacíos' },
          { descripcion: 'Asignar número correlativo y registrar en el sistema', fase: 'preparacion', critico: true, nota: '' },
          { descripcion: 'Verificar identidad y autorización del solicitante', fase: 'preparacion', critico: true, nota: '' },
          { descripcion: 'Adjuntar documentación de respaldo al registro', fase: 'preparacion', critico: false, nota: '' },
          { descripcion: 'Notificar recepción al solicitante con tiempo estimado', fase: 'preparacion', critico: false, nota: 'Plazo máximo 30 minutos' },
          { descripcion: 'Derivar al área de procesamiento correspondiente', fase: 'ejecucion', critico: true, nota: '' },
          { descripcion: 'Confirmar cierre y enviar resultado al solicitante', fase: 'cierre', critico: true, nota: '' },
        ],
      },
      {
        rol: 'Supervisor',
        descripcion_rol: 'Responsable del control de calidad y aprobación final',
        items: [
          { descripcion: 'Revisar que el procesamiento cumple con los estándares de calidad', fase: 'revision', critico: true, nota: '' },
          { descripcion: 'Validar que la documentación de respaldo está completa', fase: 'revision', critico: true, nota: 'Archivar copia digital' },
          { descripcion: 'Verificar cumplimiento regulatorio si aplica', fase: 'revision', critico: true, nota: '' },
          { descripcion: 'Aprobar o rechazar con fundamento documentado', fase: 'revision', critico: true, nota: 'Documentar razón en caso de rechazo' },
          { descripcion: 'Revisar métricas del período (semanal)', fase: 'cierre', critico: false, nota: 'Frecuencia semanal' },
        ],
      },
    ],
  },
  backlog: {
    resumen: { total_quick_wins: 3, total_proyectos_medios: 2, total_proyectos_mayores: 1, esfuerzo_total_semanas: 24 },
    iniciativas: [
      { id: 'I-01', titulo: 'Digitalizar formularios de solicitud', descripcion: 'Reemplazar formularios físicos por formularios digitales con validación automática de campos obligatorios', categoria: 'quick_win', impacto: 4, esfuerzo: 1, tiempo_estimado: '2 semanas', responsable_sugerido: 'TI + Área de proceso', beneficio_esperado: 'Eliminación de errores de transcripción y reducción de tiempo de recepción en 60%', dependencias: [] },
      { id: 'I-02', titulo: 'Implementar notificaciones automáticas por correo', descripcion: 'Configurar alertas automáticas en cada etapa del proceso para mantener informado al solicitante', categoria: 'quick_win', impacto: 3, esfuerzo: 1, tiempo_estimado: '1 semana', responsable_sugerido: 'TI', beneficio_esperado: 'Reducción de consultas de seguimiento en 70%', dependencias: ['I-01'] },
      { id: 'I-03', titulo: 'Dashboard de seguimiento en tiempo real', descripcion: 'Panel de control con estado de solicitudes, KPIs y alertas de vencimiento de SLA', categoria: 'quick_win', impacto: 4, esfuerzo: 2, tiempo_estimado: '3 semanas', responsable_sugerido: 'TI + Jefatura', beneficio_esperado: 'Visibilidad total del proceso para la jefatura', dependencias: ['I-01'] },
      { id: 'I-04', titulo: 'Automatizar validaciones de negocio', descripcion: 'Motor de reglas que valide automáticamente condiciones y requisitos del proceso', categoria: 'proyecto_medio', impacto: 5, esfuerzo: 3, tiempo_estimado: '6 semanas', responsable_sugerido: 'TI + Área funcional', beneficio_esperado: 'Reducción 90% en tiempo de validación manual', dependencias: ['I-01', 'I-02'] },
      { id: 'I-05', titulo: 'Integración con ERP corporativo', descripcion: 'Conexión bidireccional con el ERP para actualización automática de registros', categoria: 'proyecto_medio', impacto: 5, esfuerzo: 4, tiempo_estimado: '8 semanas', responsable_sugerido: 'TI', beneficio_esperado: 'Eliminación de doble digitación y sincronización automática', dependencias: ['I-04'] },
      { id: 'I-06', titulo: 'Plataforma BPM end-to-end', descripcion: 'Implementación de solución BPM completa con flujo digital, aprobaciones móviles y analytics avanzado', categoria: 'proyecto_mayor', impacto: 5, esfuerzo: 5, tiempo_estimado: '16 semanas', responsable_sugerido: 'PMO + TI + Área funcional', beneficio_esperado: 'Transformación completa: 75% reducción tiempo de ciclo, trazabilidad 100%', dependencias: ['I-01', 'I-02', 'I-03', 'I-04', 'I-05'] },
    ],
  },
  cinco_porques: {
    analisis: [
      {
        problema: 'Tiempo de ciclo del proceso superior al objetivo',
        impacto: 'Incumplimiento de SLAs y baja satisfacción del cliente interno',
        cadena: [
          { porque: 'El proceso tarda más de lo esperado en completarse' },
          { porque: 'Existen tiempos de espera entre etapas por falta de coordinación automática' },
          { porque: 'La coordinación se realiza manualmente a través de correos y llamadas' },
          { porque: 'No existe un sistema de workflow que automatice las transiciones' },
          { porque: 'El proceso no fue diseñado con herramientas de gestión digital desde el inicio' },
        ],
        causa_raiz: 'Ausencia de herramientas de workflow y automatización en el diseño original del proceso',
        tipo_causa: 'tecnología',
        accion_correctiva: 'Implementar plataforma BPM con automatización de transiciones entre etapas y notificaciones en tiempo real',
        responsable: 'Jefe de TI + Jefe de Área',
        plazo: '3 meses',
      },
      {
        problema: 'Alta tasa de reprocesos y errores en el proceso',
        impacto: 'Costos adicionales y retrasos que afectan la productividad del equipo',
        cadena: [
          { porque: 'Los casos deben ser devueltos y corregidos con frecuencia' },
          { porque: 'Los errores se detectan en etapas tardías del proceso' },
          { porque: 'No existen validaciones automáticas en el origen de los datos' },
          { porque: 'El ingreso de datos es 100% manual sin controles de calidad' },
          { porque: 'El proceso fue diseñado sin considerar mecanismos de prevención de errores' },
        ],
        causa_raiz: 'Falta de controles preventivos y validaciones automáticas en el punto de ingreso de datos',
        tipo_causa: 'proceso',
        accion_correctiva: 'Incorporar validaciones automáticas de campos, reglas de negocio y alertas tempranas en el formulario de ingreso',
        responsable: 'Analista + TI',
        plazo: '2 meses',
      },
    ],
    conclusion_sistemica: 'Los principales problemas del proceso comparten una causa raíz común: el diseño sin herramientas digitales y sin controles preventivos. La solución sistémica requiere rediseño del proceso con tecnología BPM e incorporación de validaciones automáticas desde el inicio.',
  },
  acta_inicio: {
    titulo_proyecto: 'Proyecto de Mejora y Digitalización del Proceso',
    proposito: 'Transformar el proceso mediante digitalización, automatización y estandarización para mejorar la eficiencia operacional, reducir el tiempo de ciclo en un 70% y eliminar los reprocesos, generando mayor valor al cliente interno.',
    fecha_inicio: '',
    fecha_fin_estimada: '6 meses desde aprobación del proyecto',
    presupuesto_estimado: 'A definir según alcance tecnológico — referencia: 3-5x beneficio anual estimado',
    patrocinador: 'Gerente General o Gerente de Área',
    director_proyecto: 'Jefe de Área responsable del proceso',
    alcance: {
      incluye: ['Análisis y documentación del proceso actual (AS-IS)', 'Diseño del proceso futuro optimizado (TO-BE)', 'Implementación de herramienta de workflow/BPM', 'Automatización de validaciones y notificaciones', 'Integración con sistemas existentes', 'Capacitación del equipo', 'Documentación y manuales operacionales'],
      excluye: ['Rediseño de procesos adyacentes no contemplados en el alcance', 'Desarrollo de nuevos sistemas corporativos', 'Cambios en la estructura organizacional'],
    },
    objetivos: [
      { descripcion: 'Reducir el tiempo de ciclo del proceso', metrica: 'Horas promedio por transacción', meta: 'Reducción mínima del 60%' },
      { descripcion: 'Eliminar reprocesos por errores', metrica: 'Tasa de reprocesos (%)', meta: 'Menos del 5%' },
      { descripcion: 'Mejorar satisfacción del cliente interno', metrica: 'NPS interno (0-100)', meta: 'Mínimo 80 puntos' },
    ],
    supuestos: ['Disponibilidad del equipo para participar en el proyecto', 'Acceso a los sistemas tecnológicos necesarios', 'Apoyo de TI durante la implementación', 'Presupuesto aprobado según estimación'],
    restricciones: ['No interrumpir la operación durante la implementación', 'Presupuesto sujeto a aprobación de la dirección', 'Plazo máximo de 6 meses para la implementación'],
    criterios_exito: ['Proceso operando 100% en plataforma digital', 'KPIs de desempeño dentro del rango objetivo', 'Equipo capacitado y autónomo en la nueva herramienta', 'Cero interrupciones de la operación durante la implementación'],
    firmas_requeridas: ['Patrocinador del proyecto', 'Director del proyecto', 'Jefe de TI', 'Representante del Área usuaria'],
  },
  plan_pruebas: {
    resumen: 'Plan de pruebas para validar el funcionamiento correcto del proceso digitalizado, asegurando que todos los flujos, validaciones y integraciones operen según los requerimientos definidos.',
    ambiente_pruebas: 'Ambiente de QA/UAT con datos anonimizados representativos del ambiente productivo',
    responsable_pruebas: 'Analista de Procesos + Jefe de TI',
    casos: [
      { id: 'CP-01', nombre: 'Registro exitoso de solicitud estándar', tipo: 'funcional', prioridad: 'alta', precondicion: 'Usuario autenticado con permisos de solicitante', pasos: ['Acceder al portal de solicitudes', 'Completar todos los campos obligatorios', 'Adjuntar documentación requerida', 'Confirmar y enviar solicitud'], resultado_esperado: 'Solicitud registrada con número correlativo único y notificación enviada al solicitante y al analista', criterio_falla: 'No se genera el número correlativo o no se envía la notificación' },
      { id: 'CP-02', nombre: 'Validación de campos obligatorios', tipo: 'funcional', prioridad: 'alta', precondicion: 'Formulario de solicitud disponible', pasos: ['Acceder al formulario', 'Dejar campos obligatorios vacíos', 'Intentar enviar la solicitud'], resultado_esperado: 'El sistema bloquea el envío e indica los campos faltantes con mensaje claro', criterio_falla: 'El sistema acepta la solicitud incompleta o no indica los campos faltantes' },
      { id: 'CP-03', nombre: 'Flujo completo de aprobación', tipo: 'integración', prioridad: 'alta', precondicion: 'Solicitud en estado pendiente de revisión', pasos: ['El revisor recibe notificación de caso pendiente', 'Accede al caso desde la notificación', 'Revisa la información completa', 'Aprueba el caso', 'Verifica notificación al solicitante'], resultado_esperado: 'Estado actualizado a "Aprobado", solicitante notificado y registro cerrado en el sistema', criterio_falla: 'El estado no se actualiza, la notificación no llega o el registro no se cierra' },
      { id: 'CP-04', nombre: 'Flujo de rechazo con observaciones', tipo: 'funcional', prioridad: 'media', precondicion: 'Solicitud en estado pendiente de revisión', pasos: ['El revisor accede al caso', 'Selecciona la opción de rechazar', 'Ingresa las observaciones de rechazo', 'Confirma el rechazo'], resultado_esperado: 'Estado actualizado a "Rechazado", solicitante notificado con las observaciones y posibilidad de reenviar', criterio_falla: 'No se registran las observaciones o el solicitante no es notificado' },
      { id: 'CP-05', nombre: 'Prueba de usuario final (UAT)', tipo: 'usuario', prioridad: 'alta', precondicion: 'Usuario final capacitado en el nuevo sistema', pasos: ['Ejecutar caso de uso completo desde solicitud hasta cierre', 'Registrar observaciones y dificultades encontradas'], resultado_esperado: 'Usuario completa el proceso sin asistencia técnica en menos de 15 minutos', criterio_falla: 'El usuario requiere más de 2 intervenciones de soporte o supera los 15 minutos' },
    ],
    criterios_aprobacion: ['100% de los casos de alta prioridad aprobados', 'Cero errores críticos abiertos al momento del pase a producción', 'Tiempo de respuesta del sistema menor a 3 segundos en condiciones normales'],
    plan_contingencia: 'En caso de falla crítica en las pruebas, mantener el proceso manual en paralelo por 30 días adicionales mientras se corrigen los defectos. No realizar el pase a producción hasta que el 100% de los casos de alta prioridad estén aprobados.',
  },
  roadmap: {
    duracion_total_semanas: 16,
    metodologia: 'Implementación por fases con enfoque ágil, priorizando quick wins tempranos para demostrar valor y generar adopción del equipo',
    fases: [
      {
        nombre: 'Fase 1: Fundamentos y Quick Wins',
        objetivo: 'Digitalizar el proceso base y obtener victorias tempranas visibles en 4 semanas',
        semana_inicio: 1,
        semana_fin: 4,
        duracion_semanas: 4,
        actividades: ['Documentar y validar el proceso actual con el equipo', 'Implementar formularios digitales de solicitud', 'Configurar notificaciones automáticas por correo', 'Capacitar al equipo en las nuevas herramientas', 'Ejecutar primeras transacciones digitales'],
        entregables: ['Proceso documentado y validado', 'Formularios digitales operativos', 'Equipo capacitado en nivel básico'],
        hitos: ['Proceso base digitalizado (semana 3)', 'Primera transacción 100% digital ejecutada (semana 4)'],
      },
      {
        nombre: 'Fase 2: Automatización y Control',
        objetivo: 'Implementar controles automáticos, flujo de aprobación digital y métricas en tiempo real',
        semana_inicio: 5,
        semana_fin: 10,
        duracion_semanas: 6,
        actividades: ['Implementar motor de validaciones automáticas', 'Desarrollar flujo de aprobación digital', 'Crear dashboard de seguimiento y KPIs', 'Integrar con sistemas ERP existentes', 'Pruebas de integración y ajustes'],
        entregables: ['Motor de validaciones activo', 'Flujo de aprobación digital funcionando', 'Dashboard de KPIs operativo', 'Integración ERP completada'],
        hitos: ['Aprobaciones digitales activas (semana 8)', 'Dashboard de KPIs en producción (semana 10)'],
      },
      {
        nombre: 'Fase 3: Optimización y Estabilización',
        objetivo: 'Optimizar el proceso basado en datos reales y preparar al equipo para la autonomía operacional',
        semana_inicio: 11,
        semana_fin: 16,
        duracion_semanas: 6,
        actividades: ['Análisis de datos de las primeras 10 semanas', 'Ajustes y optimizaciones basadas en métricas reales', 'Capacitación avanzada al equipo', 'Documentar lecciones aprendidas y mejores prácticas', 'Transferencia de conocimiento y cierre de proyecto'],
        entregables: ['Proceso optimizado con evidencia de mejora', 'Documentación final y manuales', 'Equipo autónomo en operación', 'Informe de cierre con KPIs alcanzados'],
        hitos: ['KPIs dentro de rango objetivo (semana 14)', 'Equipo autónomo sin soporte externo (semana 16)'],
      },
    ],
    factores_exito: ['Compromiso visible de la alta dirección', 'Disponibilidad del equipo para capacitación y cambio', 'Recursos de TI asignados en tiempo y forma', 'Gestión del cambio efectiva con comunicación continua'],
    riesgos_implementacion: ['Resistencia al cambio del equipo operacional', 'Complejidad de integración con sistemas legacy existentes', 'Disponibilidad limitada de recursos de TI', 'Cambios de alcance durante la implementación'],
  },
}
